-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity DTJSCC is
port (
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    img_in_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    img_in_ce0 : OUT STD_LOGIC;
    img_in_we0 : OUT STD_LOGIC;
    img_in_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    img_in_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    img_in_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    img_in_ce1 : OUT STD_LOGIC;
    img_in_we1 : OUT STD_LOGIC;
    img_in_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    img_in_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    mm_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    mm_ce0 : OUT STD_LOGIC;
    mm_we0 : OUT STD_LOGIC;
    mm_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    mm_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    mm_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    mm_ce1 : OUT STD_LOGIC;
    mm_we1 : OUT STD_LOGIC;
    mm_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    mm_q1 : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of DTJSCC is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "DTJSCC_DTJSCC,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvp1802-lsvc4072-1LHP-i-L,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=0.000000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=0,HLS_VERSION=2023_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";



begin



    ap_done <= ap_start;
    ap_idle <= ap_const_logic_1;
    ap_ready <= ap_start;
    img_in_address0 <= ap_const_lv10_0;
    img_in_address1 <= ap_const_lv10_0;
    img_in_ce0 <= ap_const_logic_0;
    img_in_ce1 <= ap_const_logic_0;
    img_in_d0 <= ap_const_lv32_0;
    img_in_d1 <= ap_const_lv32_0;
    img_in_we0 <= ap_const_logic_0;
    img_in_we1 <= ap_const_logic_0;
    mm_address0 <= ap_const_lv4_0;
    mm_address1 <= ap_const_lv4_0;
    mm_ce0 <= ap_const_logic_0;
    mm_ce1 <= ap_const_logic_0;
    mm_d0 <= ap_const_lv32_0;
    mm_d1 <= ap_const_lv32_0;
    mm_we0 <= ap_const_logic_0;
    mm_we1 <= ap_const_logic_0;
end behav;
