// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="DTJSCC_DTJSCC,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvp1802-lsvc4072-1LHP-i-L,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=0.000000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=0,HLS_VERSION=2023_2}" *)

module DTJSCC (
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        img_in_address0,
        img_in_ce0,
        img_in_we0,
        img_in_d0,
        img_in_q0,
        img_in_address1,
        img_in_ce1,
        img_in_we1,
        img_in_d1,
        img_in_q1,
        mm_address0,
        mm_ce0,
        mm_we0,
        mm_d0,
        mm_q0,
        mm_address1,
        mm_ce1,
        mm_we1,
        mm_d1,
        mm_q1
);


input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] img_in_address0;
output   img_in_ce0;
output   img_in_we0;
output  [31:0] img_in_d0;
input  [31:0] img_in_q0;
output  [9:0] img_in_address1;
output   img_in_ce1;
output   img_in_we1;
output  [31:0] img_in_d1;
input  [31:0] img_in_q1;
output  [3:0] mm_address0;
output   mm_ce0;
output   mm_we0;
output  [31:0] mm_d0;
input  [31:0] mm_q0;
output  [3:0] mm_address1;
output   mm_ce1;
output   mm_we1;
output  [31:0] mm_d1;
input  [31:0] mm_q1;

assign ap_done = ap_start;

assign ap_idle = 1'b1;

assign ap_ready = ap_start;

assign img_in_address0 = 10'd0;

assign img_in_address1 = 10'd0;

assign img_in_ce0 = 1'b0;

assign img_in_ce1 = 1'b0;

assign img_in_d0 = 32'd0;

assign img_in_d1 = 32'd0;

assign img_in_we0 = 1'b0;

assign img_in_we1 = 1'b0;

assign mm_address0 = 4'd0;

assign mm_address1 = 4'd0;

assign mm_ce0 = 1'b0;

assign mm_ce1 = 1'b0;

assign mm_d0 = 32'd0;

assign mm_d1 = 32'd0;

assign mm_we0 = 1'b0;

assign mm_we1 = 1'b0;

endmodule //DTJSCC
